file:
  /etc/filebeat/filebeat.yml:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/bin/ossec-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/ossec.conf:
    exists: true
    mode: "0660"
    owner: root
    group: ossec
    filetype: file
    contains: []
package:
  filebeat:
    installed: true
    versions:
    - 7.9.1
  wazuh-manager:
    installed: true
    versions:
    - 4.0.3
port:
  tcp:1514:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
user:
  ossec:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
  ossecm:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
  ossecr:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
group:
  ossec:
    exists: true
process:
  filebeat:
    running: true
  ossec-analysisd:
    running: true
  ossec-authd:
    running: true
  ossec-syscheckd:
    running: true
  s6-supervise:
    running: true
  wazuh-db:
    running: true
  wazuh-modulesd:
    running: true
