version: '2'

services:
  wazuh:
    build: wazuh/
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514/udp:1514/udp"
      - "1515:1515"
#      - "514/udp:514/udp"
      - "55000:55000"
    networks:
      - docker_elk
    volumes:
      - /mnt/data/ossec/wazuh:/var/ossec/data
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:5.1.2
    restart: always
    command: elasticsearch -E node.name="node-1" -E cluster.name="wazuh" -E network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms64g -Xmx64g"
    volumes:
      - /mnt/data/ossec/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
#    ports:
#      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  kibana:
    build: kibana/
    restart: always
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    entrypoint: sh wait-for-it.sh elasticsearch

networks:
  docker_elk:
    driver: bridge
