name: Wazuh Docker pipeline

on: [push]

jobs:
  build-stack:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build the docker-compose stack
      run: docker-compose -f build-from-sources.yml up -d --build

    - name: Check running containers
      run: docker ps -a

    - name: Shutdown the stack
      run: docker-compose -f build-from-sources.yml kill

    - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: v0.3.16

    - name: Execute Goss tests
        run: dgoss run wazuh/wazuh-odfe:dev-version
        env:
          GOSS_FILE: .goss.yaml
