name: Docker Image CI

on:
  push:
    branches: [ feature-github-actions ]
  pull_request:
    branches: [ feature-github-actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build wazuh --file Dockerfile --tag wazuh:$(date +%s)