name: Wazuh Docker pipeline

on: [push]

jobs:
  build-stack:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build the docker-compose stack
      run: ./build.sh

    - name: Check running containers
      run: docker ps -a

    - name: Install Goss
      uses: e1himself/goss-installation-action@v1.0.3
      with:
        version: v0.3.16

    - name: Execute Goss tests (wazuh-odfe)
      run: dgoss run wazuh/wazuh-manager:4.3.1-dev
      env:
        GOSS_SLEEP: 30
        GOSS_FILE: .github/.goss.yaml